### ISSUE TITLE
Move mcabber-auto-esc into separate binary (or plugin for mcabber?)

### ISSUE THREAD

**Issue by seletskiy** [kovetskiy/dotfiles#1]

**Comment by kovetskiy** [comment]
Cannot be plugin, because mcabber headers does not provide methods which can do this. So, there is two ways:
1. plugin with strange behaviour (get pid, get parent (terminal), check focus, do actions)
2. patch mcabber

or of course seperate binary

Guesses?

**Comment by seletskiy** [comment]
You can use `xdo` bindings: https://github.com/jordansissel/xdotool/blob/master/xdo.h (package `xdotool-git` in AUR).

There is method `xdo_wait_for_window_focus`, which can be used to wait until focus changed, and then you just call some function from `mcabber/screen.h` to hide chat window.

**Comment by kovetskiy** [comment]
Hmm, I found interesting method in `mcabber/commands.h` - `do_chat_disable(char *arg);`. Yes, I think I implement this awesome plugin.

**Comment by kovetskiy** [comment]
https://github.com/kovetskiy/mcabber-focus
